#!/bin/bash


STARTADDRA='0x0800c000'
STARTADDRB='0x0802c000'
STARTADDRC='0x08047000'
STM32FLASH="stm32flash"
SERIALPORT="/dev/ttyUSB0"
OBJCOPY="arm-none-eabi-objcopy"
declare -u UPPERCASEFILE
MASTERFILE=$1
UPPERCASEFILE=${MASTERFILE}
ENDFILESTR=':00000001FF'
SPLITSTR1=':020000040802'
SPLITSTR2=':020000040804'
#echo ${MASTERFILE}
#echo ${DIR}

SPLITLINE=`cat ${MASTERFILE}.hex | grep ^${SPLITSTR1} -n | cut -d':' -f1`
#echo ${SPLITLINE}
LASTLINE=`cat ${MASTERFILE}.hex | grep ^${ENDFILESTR} -n | cut -d':' -f1`
#echo ${LASTLINE}
SPLITLINE1=`expr ${SPLITLINE} - 1`
#echo ${SPLITLINE1}
head -n ${SPLITLINE1} < ${MASTERFILE}.hex > ${UPPERCASEFILE}A.HEX
#echo ${SPLITLINE1}
echo ${ENDFILESTR} >> ${UPPERCASEFILE}A.HEX
echo ${STARTADDRA} > ${UPPERCASEFILE}A.ADR
tail -n +${SPLITLINE} < ${MASTERFILE}.hex > ${MASTERFILE}_TMPB.hex
#echo ${SPLITLINE}
echo ${STARTADDRB} > ${UPPERCASEFILE}B.ADR
#echo ${SPLITLINE}

SPLITLINE2=`cat ${MASTERFILE}_TMPB.hex | grep ^${SPLITSTR2} -n | cut -d':' -f1`
#echo ${SPLITLINE}
#echo ${LASTLINE}
SPLITLINE3=`expr ${SPLITLINE2} - 1`
#echo ${SPLITLINE1}
head -n ${SPLITLINE3} < ${MASTERFILE}_TMPB.hex > ${UPPERCASEFILE}B.HEX
#echo ${SPLITLINE1}
echo ${ENDFILESTR} >> ${UPPERCASEFILE}B.HEX
echo ${STARTADDRB} > ${UPPERCASEFILE}B.ADR
tail -n +${SPLITLINE2} < ${MASTERFILE}_TMPB.hex > ${UPPERCASEFILE}C.HEX
#echo ${SPLITLINE}
echo ${STARTADDRC} > ${UPPERCASEFILE}C.ADR

${OBJCOPY} -I ihex -O binary ${UPPERCASEFILE}A.HEX ${UPPERCASEFILE}A.BIN
${OBJCOPY} -I ihex -O binary ${UPPERCASEFILE}B.HEX ${UPPERCASEFILE}B.BIN
${OBJCOPY} -I ihex -O binary ${UPPERCASEFILE}C.HEX ${UPPERCASEFILE}C.BIN

rm ${UPPERCASEFILE}A.HEX ${UPPERCASEFILE}B.HEX ${UPPERCASEFILE}C.HEX ${MASTERFILE}_TMPB.hex

#mv ${MASTERFILE}.hex ${UPPERCASEFILE}.HEX

echo " ./${STM32FLASH} -v ${SERIALPORT} -w ${UPPERCASEFILE}A.BIN -S ${STARTADDRA}:`ls -l ${UPPERCASEFILE}A.BIN | cut -d\" \" -f5`" > flashall.sh
echo " ./${STM32FLASH} -v ${SERIALPORT} -w ${UPPERCASEFILE}B.BIN -S ${STARTADDRB}:`ls -l ${UPPERCASEFILE}B.BIN | cut -d\" \" -f5`" >> flashall.sh
echo " ./${STM32FLASH} -v ${SERIALPORT} -w ${UPPERCASEFILE}C.BIN -S ${STARTADDRC}:`ls -l ${UPPERCASEFILE}C.BIN | cut -d\" \" -f5`" >> flashall.sh

chmod +x flashall.sh